config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledges#timeline'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'profile', on: :member
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get :favorite, on: :collection
    get :result, on: :collection
  end
  resources :categories, only: %i[index show create]
  resources :knowledges do
    resources :comments, only: %i[new create edit update destroy]
    get 'timeline', on: :collection
  end
  resources :favorites, only: %i[create destroy]
  resources :notifications, only: :index
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :knowledge
  has_many :notifications, dependent: :destroy
  
  validates :comment, presence: true, length: { maximum: 150 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[edit update destroy]
  before_action :set_knowledge, only: %i[new create edit]
  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = @knowledge.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      @knowledge.create_notification_comment!(current_user, @comment.id)
      redirect_to knowledge_path(@knowledge), notice: "コメントを作成しました"
    else
      render "comments/new", status: :unprocessable_entity
    end
  end
  
  def edit
    if @comment.user != current_user
      redirect_to knowledge_path(@knowledge), alert: "ページを閲覧する権限がありません"
    end
  end
  
  def update
    if @comment.update(comment_params)
      redirect_to knowledge_path(@comment.knowledge), notice: "コメントを編集しました"
    else
      render "knowledges/show", status: :unprocessable_entity
    end
  end

  def destroy
    if @comment.user == current_user
      @comment.destroy
      redirect_to request.referer, notice: "コメントを削除しました"
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
  
  def set_knowledge
    @knowledge = Knowledge.find(params[:knowledge_id])
  end
  
  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_form.html.erb
<div class="text-danger text-center mt-2">
  <%= render "layouts/error_messages", model: @comment %>
</div>
<%= form_with model: [@knowledge , @comment], local: true do |f| %>

  <div class="offset-2 col-8 mt-2">
    <%= f.label :comment, "コメント", class: "form-label fw-bolder" %>
  </div>
  
  <div class="offset-2 col-8">
    <%= f.text_area :comment, class: "form-control", rows:"2" %>
  </div>
  
  <div class="text-center my-2">
    <%= f.submit "Submit", class: "btn btn-outline-success" %>
  </div>

<% end %>

app/views/comments/_comment_list.html.erb
<div class="card shadow-lg offset-3 col-6 mt-3 mb-3">
  <div class="col-3 mt-2"><%= link_to "コメント作成", new_knowledge_comment_path(@knowledge), class: "text-decoration-none" %></div>
  <% @comments.each do |c| %>
    <div class="row">
      <div class="mt-3 col-11">
        <%= c.comment %>
      </div>
      <% if c.user == current_user %>
        <div class="dropdown col-1">
          <a class="text-decoration-none fw-bold link-dark" type="button" id="comment_dropdown" data-bs-toggle="dropdown" aria-expanded="false">...</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="comment_dropdown">
            <li><%= link_to "edit", edit_knowledge_comment_path(@knowledge, c), class: "dropdown-item" %></li>
            <li><%= link_to "delete", knowledge_comment_path(@knowledge, c), data: { turbo_method: :delete, turbo_confirm: "コメントを削除しますか?" }, class: "dropdown-item" %></li>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="text-end mt-1"><%= link_to c.user.name, user_path(c.user.id), class: "text-decoration-none" %></div>
    <div class="border-bottom mt-2"></div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="card shadow-lg offset-3 col-6 mt-5">
  <%= render "comments/comment_form" %>
</div>

app/views/comments/new.html.erb
<div class="card shadow-lg offset-3 col-6 mt-5">
  <%= render "comments/comment_form" %>
</div>