config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledges#timeline'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'profile', on: :member
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get :favorite, on: :collection
    get :result, on: :collection
  end
  resources :categories, only: %i[index show create]
  resources :knowledges do
    resources :comments, only: %i[new create edit update destroy]
    get 'timeline', on: :collection
  end
  resources :favorites, only: %i[create destroy]
  resources :notifications, only: :index
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line google_oauth2]
  # フォロー機能の関連付け
  has_many :knowledges, dependent: :destroy
  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # お気に入り機能の関連付け
  has_many :favorites, dependent: :destroy
  has_many :favorite_knowledges, through: :favorites, source: :knowledge
  
  # コメント機能の関連付け
  has_many :comments, dependent: :destroy
  
  # 通知機能の関連付け
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  mount_uploader :profile_image, ProfileImageUploader

  validates :introduction, presence: false, length: { maximum: 150 }

  # フォローした時の処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # お気に入りに入れる処理
  def favorite(knowledge)
    favorite_knowledges << knowledge
  end

  # お気に入りから外す処理
  def unfaborite(knowledge)
    favorite_knowledges.destroy(knowledge)
  end

  # お気に入りに入れているか判定
  def favorite?(knowledge)
    favorite_knowledges.include?(knowledge)
  end
  
  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
        notification.save if notification.valid?
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      callback_for(:google)
    end
    
    def callback_for(provider)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
    end
    
    def failure
      redirect_to root_path
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    protected

    # 必須  更新（編集の反映）時にパスワード入力を省く
    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    # 任意  更新後のパスを指定
    def after_update_path_for(_resource)
      timeline_knowledges_path
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update profile set_q]
  before_action :set_q, only: [:profile]
  before_action :set_q_user, only: %i[index result]
  
  def index
    @users = @q.result.page(params[:page])
  end
  
  def show
    @user_knowledges = @user.knowledges.order(created_at: 'desc').page(params[:page])
    return unless @user == current_user

    redirect_to profile_user_path
  end

  def edit
    return unless current_user != @user

    redirect_to profile_user_path, alert: '自分以外のプロフィールは作成できません。'
  end

  def update
    if @user.update(user_params_update)
      redirect_to profile_user_path, notice: 'プロフィールを保存しました。'
    else
      render 'users/edit', status: :unprocessable_entity
    end
  end

  def profile
    if current_user != @user
      redirect_to user_path
    else
      @profile_knowledges = @q.result.order(created_at: 'desc').page(params[:page])
    end
  end

  def favorite
    @favorites = current_user.favorite_knowledges.includes(:user).order(created_at: 'desc').page(params[:page])
  end
  
  def result
    @users = @q.result.page(params[:page])
  end

  private

  def set_q
    @q = @user.knowledges.ransack(params[:q])
  end
  
  def set_q_user
    @q = User.ransack(params[:q])
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params_update
    params.require(:user).permit(:introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_knowledge.html.erb
<%= link_to knowledge_path(knowledge.id), class: "card offset-3 col-6 mt-3 mb-2 shadow-lg text-decoration-none btn text-start" do %>
  <div class="row">
    <div class="mt-2 ms-2 col-5 fw-bolder"><%= knowledge.title %></div>
    <div class="text-end col-7 fw-light text-secondary" style="font-size: 14px;"><span class="position-absolute top-0 end-0 mt-3 me-4"><%= knowledge.category.category_name %></span></div>
    <div class="mt-4 offset-1 mb-2 col-10 text-truncate"><%= knowledge.body %></div>
    <div class="text-secondary text-end mt-4"><%= knowledge.created_at.strftime('%Y/%m/%d %H:%M') %></div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="card offset-3 col-6 shadow-lg mt-5">
    <div class="text-danger text-center mt-4">
      <%= render "layouts/error_messages", model: @user %>
    </div>
    <%= form_with model: @user, local: true do |f| %>
      <div class="row">
      
        <div class="offset-2 col-8">
          <%= f.label :profile_image, "プロフィール画像", class: "form-label" %>
          <%= f.file_field :profile_image, class: "form-control" %>
        </div>
        
        <div class="offset-2 col-8 mt-2">
          <%= f.label :introduction, "プロフィール文", class: "form-label" %><br>
          <%= f.text_area :introduction, class: "form-control", rows:"4" %>
        </div>
        
        <div class="text-center mt-3 mb-4">
          <%= f.submit "Create", class: "btn btn-outline-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/favorite.html.erb
<h5 class="offset-3 col-6 mt-4 fw-bolder text-primary mb-3"><span class="ms-3">お気に入りリスト</span></h5>
<%= render partial: "knowledge", collection: @favorites %>
<div class="offset-lg-5 offset-4 mt-4">
  <%= paginate @favorites, theme: 'bootstrap-5' %>
</div>

app/views/users/index.html.erb
<div class="card offset-3 col-6 shadow-lg mt-5">
  <%= search_form_for @q, url: result_users_path do |f| %>
    <div class="mt-3 offset-3"><%= f.label :name_cont, '名前検索', class: "form-label" %></div>
    <div class="offset-3 col-6"><%= f.search_field :name_cont, class:"form-control border-dark" %></div>
    <div class="text-center mt-3"><%= f.submit 'Search', class: "btn btn-outline-dark btn-sm mb-3" %></div>
  <% end %>
</div>

app/views/users/profile.html.erb
<div class="row">
  <div class="card offset-3 col-6 mt-3 shadow-lg">
    <div class="row">
      <% if @user.profile_image? %>
        <div class="mt-2 col-2">
          <%= image_tag @user.profile_image.url, class: "rounded" %>
        </div>
      <% end %>
      <div class="mt-3 ms-5 col-9">
        <% if @user.introduction.nil? %>
          <div><%= @user.introduction %></div>
        <% else %>
          <div><%= safe_join(@user.introduction.split("\n"),tag(:br)) %></div>
        <% end %>
        <%= link_to "プロフィール作成", edit_user_path(@user.id) %>
      </div>
    </div>
    <div class="fw-bolder mt-1 ms-4"><%= @user.name %></div>
    <% if @user.birth_date.nil? %>
      <div class="mt-2 ms-3 col-5" style="font-size: 13px;">誕生日を設定されていません</div>
    <% else %>
      <div class="mt-2 ms-3 col-5">Birthday : <%= @user.birth_date.strftime("%Y年%m月%d日") %></div>
    <% end %>
    <div class="my-2"><%= render "relationships/follow_list" %></div>
  </div>
  <div class="card offset-3 col-6 shadow-lg my-4">
    <%= search_form_for @q, url: profile_user_path do |f| %>
      <div class="row">
        <div class="mt-2 offset-3"><%= f.label :title_cont, 'タイトル検索', class: "form-label" %></div>
        <div class="offset-3 col-6"><%= f.search_field :title_cont, class:"form-control border-dark" %></div>
        <div class="mt-2 offset-3"><%= f.label :body_cont, '本文検索', class: "form-label" %></div>
        <div class="offset-3 col-6"><%= f.search_field :body_cont, class:"form-control border-dark" %></div>
        <div class="mt-2 text-center"><%= f.submit 'Search', class: "btn btn-outline-dark btn-sm mb-3" %></div>
      </div>
    <% end %>
  </div>
  <div>
    <%= render partial: "knowledge", collection: @profile_knowledges %>
  </div>
  <div class="offset-lg-5 offset-4 mt-4">
    <%= paginate @profile_knowledges, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/users/result.html.erb
<div class="card shadow-lg offset-3 col-6 mt-5">
  <% @users.each do |u| %>
    <div class="offset-3 mt-2">
      <% if current_user != u %>
        <% if u.name.empty? %>
          <span>・<%= link_to "名無し#{u.id}", user_path(u), class: "text-decoration-none" %></span>
        <% else %>
          <span>・<%= link_to u.name, user_path(u.id), class: "text-decoration-none" %></span>
        <% end %>
        <% if current_user.following?(u) %>
          <span class="ms-2"><%= link_to "フォローを外すー", user_relationship_path(u.id, u.id), data: { turbo_method: :delete, turbo_confirm: "フォローを外しますか?" }, class: "btn btn-outline-primary btn-sm" %></span>
        <% else %>
          <span class="ms-2"><%= link_to "フォローする＋", user_relationships_path(u.id), data: { turbo_method: :post }, class: "btn btn-outline-primary btn-sm" %></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="offset-lg-5 offset-4 mt-3">
    <%= paginate @users, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="card offset-3 col-6 mt-5 mb-2 shadow-lg">
    <div class="row">
      <% if @user.profile_image? %>
        <div class="mt-2 col-2">
          <%= image_tag @user.profile_image.url, class: "rounded" %>
        </div>
      <% end %>
      <div class="mt-3 ms-5 col-9">
        <% if @user.introduction.nil? %>
          <div><%= @user.introduction %></div>
        <% else %>
          <div><%= safe_join(@user.introduction.split("\n"),tag(:br)) %></div>
        <% end %>
      </div>
    </div>
    <div class="mt-2">
      <span class="fw-bolder ms-3"><%= @user.name %></span>
      <% if current_user.following?(@user) %>
        <span class="mb-2 ms-2"><%= link_to "ー", user_relationship_path(@user.id), data: { turbo_method: :delete, turbo_confirm: "フォローを外しますか?" }, class: "btn btn-outline-primary btn-sm" %></span>
      <% else %>
        <span class="mb-2 ms-2"><%= link_to "＋", user_relationships_path(@user.id), data: { turbo_method: :post }, class: "btn btn-outline-primary btn-sm" %></span>
      <% end %>
    </div>
    <% if @user.birth_date.nil? %>
      <div class="mt-2 ms-3 col-5" style="font-size: 13px;">誕生日を設定されていません</div>
    <% else %>
      <div class="mt-2 ms-3 col-5">Birthday : <%= @user.birth_date.strftime("%Y年%m月%d日") %></div>
    <% end %>
    <div class="mb-3"><%= render "relationships/follow_list" %></div>
  </div>
  <div>
    <%= render partial: "knowledge", collection: @user_knowledges %>
  </div>
  <div class="offset-lg-5 offset-4 mt-4">
    <%= paginate @user_knowledges, theme: 'bootstrap-5' %>
  </div>
</div>