config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledges#timeline'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'profile', on: :member
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get :favorite, on: :collection
    get :result, on: :collection
  end
  resources :categories, only: %i[index show create]
  resources :knowledges do
    resources :comments, only: %i[new create edit update destroy]
    get 'timeline', on: :collection
  end
  resources :favorites, only: %i[create destroy]
  resources :notifications, only: :index
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/knowledge.rb
# frozen_string_literal: true

class Knowledge < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }, uniqueness: { scope: %i[category_id user_id] }
  validates :body, presence: true
  # validates :url, format: /\A#{URI::regexp(%w(http https))}\z/

  belongs_to :category
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(knowledge_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end
  
  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、1つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
        knowledge_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: 'comment'
      )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/knowledges_controller.rb
# frozen_string_literal: true

class KnowledgesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_knowledge, only: %i[show edit update destroy]
  before_action :set_q, only: [:index]

  def index
    @knowledges = @q.result.where(user_id: [current_user.id,
                                            *current_user.following_ids]).order(created_at: 'desc').page(params[:page])
  end

  def new
    @knowledge = Knowledge.new
  end

  def create
    @knowledge = Knowledge.new(knowledge_params)
    @knowledge.user = current_user
    if @knowledge.save
      redirect_to knowledges_path, notice: 'ナレッジを作成しました。'
    else
      @knowledges = Knowledge.all
      render 'knowledges/new', status: :unprocessable_entity
    end
  end

  def show
    @comments = @knowledge.comments
  end
    
  def edit
    if current_user != @knowledge.user
      redirect_back fallback_location: knowledge_path, notice: "ページを閲覧する権限がありません"
    end
  end

  def update
    if @knowledge.update(knowledge_params)
      redirect_to knowledge_path, notice: 'ナレッジを編集しました。'
    else
      render 'knowledges/edit', status: :unprocessable_entity
    end
  end

  def destroy
    if current_user != @knowledge.user
      redirect_back fallback_location: knowledge_path, notice: "削除できません"
    else
      @knowledge.destroy
      redirect_to knowledges_path, notice: '削除しました。'
    end
  end

  def timeline
    @knowledges = Knowledge.order(created_at: 'desc').page(params[:page])
  end

  private

  def set_q
    @q = Knowledge.ransack(params[:q])
  end

  def set_knowledge
    @knowledge = Knowledge.find(params[:id])
  end

  def knowledge_params
    params.require(:knowledge).permit(:title, :body, :url, :category_id)
  end
end

app/helpers/knowledges_helper.rb
# frozen_string_literal: true

module KnowledgesHelper
end

app/views/knowledges/_knowledge_form.html.erb
<%= form_with model: @knowledge, local: true do |f| %>
  <div class="row">
    <div class="offset-2 col-8 mt-3">
      <%= f.label :title, "タイトル", class: "form-label" %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
  
    <div class="offset-2 col-8 mt-2">
      <%= f.label :body, "本文", class: "form-label" %><br>
      <%= f.text_area :body, class: "form-control", rows: 4 %>
    </div>
    
    <div class="offset-2 col-8 mt-2">
      <%= f.label :url, "URL", class: "form-label" %><br>
      <%= f.text_area :url, class: "form-control", rows: 3 %>
    </div>
    
    <div class="offset-2 col-8 mt-2">
      <%= f.label :category_id, "カテゴリー", class: "form-label" %><br>
      <%= f.collection_select :category_id, Category.all, :id, :category_name, { prompt: '選択してください' }, class: "form-select" %>
    </div>
    
    <div class="mt-3 mb-4 text-center">
      <%= f.submit "Submit", class: "btn btn-outline-success col-3" %>
    </div>
  </div>
<% end %>

app/views/knowledges/_knowledge_search.html.erb
<div class="row">
  <% @knowledges.each do |k| %>
    <%= link_to knowledge_path(k.id), class: "text-decoration-none card offset-3 col-6 mt-5 mb-2 shadow-lg btn text-start" do %>
      <div class="row">
        <div class="mt-2 ms-2 col-5 fw-bolder text-dark"><%= k.title %></div>
        <div class="text-end col-7 fw-light text-secondary" style="font-size: 14px;"><span class="position-absolute top-0 end-0 mt-3 me-4"><%= k.category.category_name %></span></div>
        <div class="mt-4 offset-1 mb-2 col-10 text-truncate text-dark"><%= k.body %></div>
        <div class="text-primary text-end"><%= k.user.name %>さん</div>
        <div class="text-secondary text-end"><%= k.created_at.strftime('%Y/%m/%d %H:%M') %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/knowledges/_knowledges.html.erb
<div class="row">
  <% @knowledges.each do |k| %>
    <%= link_to knowledge_path(k.id), class: "text-decoration-none card offset-3 col-6 mt-5 mb-2 shadow-lg btn text-start" do %>
      <div class="row">
        <div class="mt-2 ms-2 col-5 fw-bolder"><%= k.title %></div>
        <div class="text-end col-7 fw-light text-secondary" style="font-size: 14px;"><span class="position-absolute top-0 end-0 mt-3 me-4"><%= k.category.category_name %></span></div>
        <div class="mt-4 offset-1 mb-2 col-10 text-truncate"><%= k.body %></div>
        <div class="text-primary text-end"><%= k.user.name %>さん</div>
        <div class="text-secondary text-end"><%= k.created_at.strftime('%Y/%m/%d %H:%M') %></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/knowledges/edit.html.erb
<div class="card offset-2 col-8 shadow-lg mt-5">
  <h3 class="offset-2 mt-3 fw-bolder">Edit</h3>
  <div class="text-danger text-center mt-4">
    <%= render "layouts/error_messages", model: @knowledge %>
  </div>
  <%= render "knowledge_form" %>
</div>

app/views/knowledges/index.html.erb
<div class="row">
  <div class="row border-bottom border-dark">
    <div class="offset-4 col-3 my-1 mt-3"><%= link_to "index", knowledges_path, class: "text-decoration-none link-dark" %></div>
    <div class="col-3 my-2 mt-3"><%= link_to "new", new_knowledge_path, class: "text-decoration-none link-dark" %></div>
  </div>
  <div class="mt-3">
    <%= search_form_for @q, url: knowledges_path do |f| %>
      <div class="row">
        <div class="offset-2 col-1 mt-1"><%= f.label :title_cont, 'タイトル', class: "form-label" %></div>
        <div class="col-2"><%= f.search_field :title_cont, class: "form-control border-dark" %></div>
        <div class="col-1 mt-1"><%= f.label :body_cont, '本文', class: "form-label ms-4" %></div>
        <div class="col-2"><%= f.search_field :body_cont, class: "form-control border-dark" %></div>
        <div class="col-1 mt-1 ms-4"><%= f.submit 'Search', class: "btn btn-outline-dark btn-sm" %></div>
      </div>
    <% end %>
  </div>
  <div>
    <%= render "knowledges" %>
  </div>
  <div class="offset-lg-5 offset-4 mt-4">
    <%= paginate @knowledges, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/knowledges/new.html.erb
<div class="row">
    <div class="row border-bottom border-dark">
      <div class="offset-4 col-3 my-1 mt-3"><%= link_to "index", knowledges_path, class: "text-decoration-none link-dark" %></div>
      <div class="col-3 my-2 mt-3"><%= link_to "new", new_knowledge_path, class: "text-decoration-none link-dark" %></div>
    </div>
  <div class="card offset-3 col-6 shadow-lg mt-5">
     <div class="text-danger text-center mt-4">
      <%= render "layouts/error_messages", model: @knowledge %>
    </div>
    <%= render "knowledge_form" %>
  </div>
</div>

app/views/knowledges/show.html.erb
<div class="row">
  <div class="card offset-3 col-6 shadow-lg mt-5">
    <div class="row">
      <div class="mt-3 ms-2 col-5 fw-bolder">
        <%= @knowledge.title %>
        <% if current_user.favorite?(@knowledge) %>
          <%= link_to 'ー🖤️', favorite_path(current_user.favorites.find_by(knowledge_id: @knowledge.id)),id: "js-bookmark-button-for-knowledge-#{@knowledge.id}", data: { turbo_method: :delete }, class: "text-decoration-none" %>
        <% else %>
          <%= link_to '＋❤️', favorites_path(knowledge_id: @knowledge.id), id: "js-bookmark-button-for-knowledge-#{@knowledge.id}", data: { turbo_method: :post }, class: "text-decoration-none" %>
        <% end %>
      </div>
      <div class="mt-3 col-7 fw-light"><span class="position-absolute top-0 end-0 mt-3 me-4"><%= link_to @knowledge.category.category_name, category_path(@knowledge.category.id), class: "link-secondary text-decoration-none" %></span></div>
      <div class="mt-3"><%= @knowledge.body %></div>
      <div class="mt-3 mb-4"><%= raw Rinku.auto_link(@knowledge.url, :all, 'target="_blank"') %></div>
      <div class="text-end text-secondary"><%= @knowledge.created_at.strftime('%Y/%m/%d %H:%M') %></div>
      <% if @knowledge.user.id != current_user.id %>
        <div class="text-end mt-1 mb-2"><%= link_to @knowledge.user.name, user_path(@knowledge.user.id), class: "text-decoration-none" %>
          <% if current_user.following?(@knowledge.user) %>
            <span class="mb-2"><%= link_to "ー", user_relationship_path(@knowledge.user.id), data: { turbo_method: :delete, turbo_confirm: "フォロー外しますか?" }, class: "btn btn-outline-primary btn-sm" %></span>
          <% else %>
            <span class="mb-2"><%= link_to "＋", user_relationships_path(@knowledge.user.id), data: { turbo_method: :post }, class: "btn btn-outline-primary btn-sm" %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% if @knowledge.user == current_user %>
    <div class="row card offset-3 col-6 shadow-lg mt-3 mb-5">
      <div class="text-center my-3">
        <%= link_to "Edit", edit_knowledge_path(@knowledge.id), class: "btn btn-outline-success col-3 me-3" %>
        <%= link_to "Delete", knowledge_path(@knowledge.id), data: { turbo_method: :delete, turbo_confirm: "削除しますか?" }, status: :see_other, class: "btn btn-outline-danger col-3" %>
      </div>
    </div>
  <% end %>
  
  <%= render "comments/comment_list" %>
</div>

app/views/knowledges/timeline.html.erb
<div class="row">
  <%= render "knowledges" %>
  <div class="offset-lg-5 offset-4 mt-4">
    <%= paginate @knowledges, theme: 'bootstrap-5' %>
  </div>
</div>