config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'knowledges#timeline'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'profile', on: :member
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
    get :favorite, on: :collection
    get :result, on: :collection
  end
  resources :categories, only: %i[index show create]
  resources :knowledges do
    resources :comments, only: %i[new create edit update destroy]
    get 'timeline', on: :collection
  end
  resources :favorites, only: %i[create destroy]
  resources :notifications, only: :index
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |msg| %>
    <div><%= msg %></div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand navbar-light" style="background-color: #DAF981;">
    <div class="container-fluid">
      <%= link_to "My index", root_path, class: "navbar-brand py-2 ms-2" %>
      <ul class="navbar-nav me-auto mb-lg-0">
        <li class="nav-item">
          <%= link_to "Category", categories_path, class: "nav-link active ms-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Knowledge", knowledges_path, class: "nav-link active ms-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Favorite", favorite_users_path, class: "nav-link active ms-2" %>
        </li>
      </ul>
      <div class="d-flex dropdown nav-item">
        <% if unchecked_notifications.any? %>
          <%= link_to notifications_path, class: "me-4 text-decoration-none" do %>
            <%= image_tag "bell.png", :size =>'25x25' %><span style="color: orange;">●</span>
          <% end %>
        <% else %>
          <%= link_to notifications_path, class: "me-2" do %>
            <%= image_tag "bell.png", :size =>'25x25' %>
          <% end %>
        <% end %>
        <a class="nav-link dropdown-toggle pe-3", href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if current_user.name.empty? %>
            <span style="font-size: 14px;">ユーザー情報を登録してください</span>
          <% else %>
            <%= current_user.name %>
          <% end %>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li><%= link_to "プロフィール", profile_user_path(current_user.id), class: "dropdown-item" %></li>
          <li><%= link_to "ユーザー検索", users_path, class: "dropdown-item" %></li>
          <li><%= link_to "登録情報編集", edit_user_registration_path, class: "dropdown-item" %></li>
          <li><%= link_to "ログアウト", users_sign_out_path, class: "dropdown-item" %></li>
        </ul>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand navbar-light" style="background-color: #DAF981;">
    <div class="container-fluid">
      <div class="navbar-brand py-2 ms-4">My index</div>
      <div class="d-flex dropdown nav-item">
        <div>
          <%- if controller_name != 'sessions' %>
            <%= link_to "ログイン", new_session_path(resource_name), class: "nav-link me-3" %>
          <%- elsif devise_mapping.registerable? && controller_name != 'registrations' %>
            <%= link_to "アカウント作成", new_registration_path(resource_name), class: "nav-link me-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnowledgeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= content_tag(:div, flash[:alert], class: "alert alert-danger") if flash[:alert] %>
    <%= content_tag(:div, flash[:notice], class: "alert alert-success") if flash[:notice] %>
    <%= yield %>
  </body>
</html>